import { getStore } from '@netlify/blobs';
const STORE='doze-platform';
const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const reply=(data,status=200)=>new Response(JSON.stringify(data),{status,headers});
const now=()=>new Date().toISOString();
const modules=['players','coaches','staff','members','fees','callups','attendance','calendar','news','partners','notifications','finance'];
const seedClub={id:'ac-matosinhos',name:'Atlético Clube Matosinhos',shortName:'AC Matosinhos',status:'active',plan:'trial',billingCycle:'monthly',price:0,renewalDate:'2026-09-10',trialEndsAt:'2026-09-10',adminName:'Administração ACM',adminEmail:'',primaryColor:'#071225',secondaryColor:'#2f8dff',logoUrl:'/assets/acm-logo.png',appUrl:'https://ac-matosinhos-socios-teste.netlify.app',teams:null,users:null,activeUsers:null,metricsStatus:'pending',integrationStatus:'identity',sourceProject:'AC Matosinhos V20',dataVersion:'0.2',modules:Object.fromEntries(modules.map(k=>[k,true])),notes:'Clube piloto da plataforma DOZE. Identidade e aplicação ligadas; métricas em tempo real ainda por integrar.',createdAt:'2026-08-11T10:00:00Z'};
function store(){return getStore({name:STORE,consistency:'strong'})}
async function readJson(s,key,fallback){const raw=await s.get(key);if(raw==null)return fallback;try{return JSON.parse(raw)}catch{return fallback}}
async function writeJson(s,key,value){await s.set(key,JSON.stringify(value))}
async function listJson(s,prefix){const r=await s.list({prefix});const blobs=Array.isArray(r)?r:r?.blobs||[];const values=await Promise.all(blobs.map(i=>readJson(s,typeof i==='string'?i:i.key,null)));return values.filter(Boolean)}
function requireKey(req){const expected=process.env.DOZE_ADMIN_KEY;if(!expected)return;const supplied=req.headers.get('x-doze-admin-key')||'';if(supplied!==expected)throw Object.assign(new Error('Chave de Super Admin inválida.'),{status:401})}
async function ensureSeed(s){const current=await readJson(s,`club:${seedClub.id}`,null);if(!current){await writeJson(s,`club:${seedClub.id}`,seedClub)}else if(!current.dataVersion||current.adminEmail==='admin@acmatosinhos.demo'||current.users===138){await writeJson(s,`club:${seedClub.id}`,{...current,...seedClub,notes:current.notes&&current.notes!=='Clube piloto da plataforma DOZE.'?current.notes:seedClub.notes})}const seeded=await s.get('meta:seeded');if(!seeded){await writeJson(s,'announcement:welcome',{id:'welcome',title:'AC Matosinhos ligado à DOZE Platform',audience:'AC Matosinhos',message:'Identidade e aplicação ligadas. Métricas reais serão o próximo conector.',createdAt:now()});await s.set('meta:seeded','0.2')}}
export default async (req)=>{try{if(req.method!=='POST')return reply({message:'Método não permitido'},405);requireKey(req);const body=await req.json().catch(()=>({}));const s=store();await ensureSeed(s);if(body.action==='bootstrap'){const [clubs,announcements]=await Promise.all([listJson(s,'club:'),listJson(s,'announcement:')]);clubs.sort((a,b)=>String(a.name).localeCompare(String(b.name),'pt'));announcements.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return reply({clubs,announcements})}if(body.action==='saveClub'){const club=body.club;if(!club?.id||!club?.name)return reply({message:'Clube inválido'},400);club.updatedAt=now();await writeJson(s,`club:${club.id}`,club);return reply({club})}if(body.action==='deleteClub'){if(!body.clubId)return reply({message:'Clube em falta'},400);await s.delete(`club:${body.clubId}`);return reply({ok:true})}if(body.action==='announce'){const a=body.announcement;if(!a?.id||!a?.title)return reply({message:'Comunicado inválido'},400);await writeJson(s,`announcement:${a.id}`,a);return reply({ok:true})}return reply({message:'Ação desconhecida'},400)}catch(e){return reply({message:e?.message||'Erro interno'},e?.status||500)}};
